name: sqflite_migration
description: A small library to manage sqlite migrations in flutter apps.
version: 0.1.0
author: kaiserkarel<k.l.kubat@gmail.com>
homepage: https://github.com/KaiserKarel/sqflite-migration

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">= 2.1.0 < 3.0.0"